author: Rohan Grover
email: "rohannng@gmail.com"
title: Rohan Grover
email: rohannng@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer | Tech Lead | Engineering Manager
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rohannng.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Theme
remote_theme: no-style-please

# Theme config
theme_config:
  appearance: "auto"
  show_description: true


social_links:
  github: rohannng
  stackoverflow: "127592"
  linkedin: rohangrover


