author: Rohan Grover
email: "rohannng@gmail.com"
title: Rohan Grover
description: >- # this means to ignore newlines until "baseurl:"
  engineering_manager | principal_software_engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rohangrover.xyz" # the base hostname & protocol for your site, e.g. http://example.com

favicon : "assets/images/favicon.ico"

# Theme
remote_theme: riggraz/no-style-please

# Theme config
theme_config:
  appearance: "auto"
  show_description: true


social_links:
  github: rohannng
  stackoverflow: "127592"
  linkedin: rohangrover


